/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_just_protect_runtime__Native */

#ifndef _Included_dev_just_protect_runtime__Native
#define _Included_dev_just_protect_runtime__Native
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     dev_just_protect_runtime__Native
 * Method:    nDecryptString
 * Signature: ([BI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_dev_just_protect_runtime__1Native_nDecryptString
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     dev_just_protect_runtime__Native
 * Method:    nIsDebuggerPresent
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_dev_just_protect_runtime__1Native_nIsDebuggerPresent
  (JNIEnv *, jclass);

/*
 * Class:     dev_just_protect_runtime__Native
 * Method:    nProtectMemory
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_dev_just_protect_runtime__1Native_nProtectMemory
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     dev_just_protect_runtime__Native
 * Method:    nGetHardwareId
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_dev_just_protect_runtime__1Native_nGetHardwareId
  (JNIEnv *, jclass);

/*
 * Class:     dev_just_protect_runtime__Native
 * Method:    nGetVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dev_just_protect_runtime__1Native_nGetVersion
  (JNIEnv *, jclass);

/*
 * Class:     dev_just_protect_runtime__Native
 * Method:    nGetPreciseTime
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_dev_just_protect_runtime__1Native_nGetPreciseTime
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
